export const BRAND = {
  orange: "#FF4D00",
  black: "#0a0a0a",
  steel: "#2D2D2D",
  white: "#FFFFFF",
  red: "#FF1A1A",
} as const;

export const SERVICE_CATEGORIES = [
  { name: "Home & Yard", slug: "home-yard", icon: "Home" },
  { name: "Personal Errands", slug: "personal-errands", icon: "ShoppingBag" },
  { name: "Creative & Digital", slug: "creative-digital", icon: "Palette" },
  { name: "Events", slug: "events", icon: "PartyPopper" },
  { name: "Food & Cooking", slug: "food-cooking", icon: "ChefHat" },
  { name: "Technology & IT", slug: "technology-it", icon: "Monitor" },
  { name: "Auto & Vehicle", slug: "auto-vehicle", icon: "Car" },
  { name: "Hair & Beauty", slug: "hair-beauty", icon: "Scissors" },
  { name: "Fitness & Wellness", slug: "fitness-wellness", icon: "Dumbbell" },
  { name: "Transportation", slug: "transportation", icon: "Truck" },
  { name: "Education & Tutoring", slug: "education-tutoring", icon: "GraduationCap" },
  { name: "Trades & Skilled Labor", slug: "trades-skilled", icon: "Wrench" },
  { name: "Business & Professional", slug: "business-professional", icon: "Briefcase" },
  { name: "Health & Caregiving", slug: "health-caregiving", icon: "Heart" },
  { name: "Arts & Entertainment", slug: "arts-entertainment", icon: "Music" },
  { name: "Outdoor & Sports", slug: "outdoor-sports", icon: "Mountain" },
] as const;

export const XP_ACTIONS = {
  first_gig_ever: 500,
  gig_complete: 100,
  five_star_rating: 75,
  five_gigs_milestone: 200,
  ten_gigs_milestone: 500,
  twentyfive_gigs_milestone: 1500,
  fifty_gigs_milestone: 3000,
  repeat_customer: 150,
  zero_cancellations_month: 300,
  first_job_posted: 100,
  detailed_review_left: 50,
} as const;

export const LEVELS = [
  { level: 1, title: "Task Starter", xp_required: 0 },
  { level: 2, title: "Side Hustler", xp_required: 500 },
  { level: 3, title: "Community Helper", xp_required: 1500 },
  { level: 4, title: "Trusted Tasker", xp_required: 3500 },
  { level: 5, title: "Pro Gigger", xp_required: 7500 },
  { level: 6, title: "Gig Master", xp_required: 15000 },
  { level: 7, title: "Community Pillar", xp_required: 30000 },
  { level: 8, title: "NexGigs Elite", xp_required: 50000 },
] as const;

export const PRICING_TIERS = {
  gigger: {
    free: { name: "Free Gigger", price: 0, commission: 0.05 },
    pro: { name: "Pro Gigger", price: 7.99, commission: 0.03 },
    elite: { name: "Elite Gigger", price: 14.99, commission: 0.01 },
  },
  poster: {
    free: { name: "Free", fee: 0.07 },
    premium: { name: "Premium", fee: 0.05 },
    enterprise: { name: "Enterprise", fee: 0.03 },
  },
} as const;

export function calculateFees(
  amount: number,
  giggerTier: "free" | "pro" | "elite",
  posterTier: "free" | "premium" | "enterprise"
) {
  const giggerCommission = PRICING_TIERS.gigger[giggerTier].commission;
  const posterServiceFee = PRICING_TIERS.poster[posterTier].fee;
  const posterPays = amount * (1 + posterServiceFee);
  const giggerReceives = amount * (1 - giggerCommission);
  const platformEarns = amount * posterServiceFee + amount * giggerCommission;
  return { posterPays, giggerReceives, platformEarns };
}

export const SKILL_SUGGESTIONS: Record<string, string[]> = {
  "Home & Yard": [
    "Lawn mowing", "Snow shoveling", "Pressure washing", "Interior painting", "Exterior painting",
    "Hauling & junk removal", "Furniture assembly", "TV mounting", "Moving help", "House cleaning",
    "Deep cleaning", "Window cleaning", "Carpet cleaning", "Gutter cleaning", "Landscaping",
    "Garden maintenance", "Tree trimming", "Fence repair", "Deck building", "Deck staining",
    "Drywall repair", "Wallpaper install", "Tile work", "Flooring install", "Cabinet install",
    "Shelf installation", "Door repair", "Lock change", "Garage organization", "Closet organization",
    "Home staging", "Interior decorating", "Handyman (general)", "Power tool operation",
    "Pool maintenance", "Hot tub maintenance", "Pest control (basic)",
  ],
  "Personal Errands": [
    "Grocery shopping", "Package pickup", "Package delivery", "Line waiting", "Personal shopping",
    "Pet sitting", "Dog walking", "Pet grooming (basic)", "Babysitting", "Childcare",
    "Elderly care companion", "House sitting", "Plant watering", "Mail collection",
    "Dry cleaning pickup", "Prescription pickup", "Gift wrapping", "Party supply shopping",
    "Returns & exchanges", "Furniture shopping assistant", "Closet organizing",
    "Donation drop-off", "Storage unit organizing", "Wait for service person",
  ],
  "Creative & Digital": [
    "Photography", "Videography", "Drone photography", "Graphic design", "Logo design",
    "Brand identity", "UI/UX design", "Web design", "App design", "Beat making",
    "Music production", "Audio engineering", "Mixing & mastering", "Podcast editing",
    "Mural art", "Face painting", "Illustration", "Digital art", "Animation",
    "3D modeling", "Video editing", "Motion graphics", "Social media management",
    "Content creation", "Copywriting", "Blog writing", "Ghostwriting", "Resume writing",
    "Canva design", "Flyer design", "Business card design", "T-shirt design",
    "Print on demand", "Etsy listing design", "Product photography", "Food photography",
    "Real estate photography", "Event photography", "Portrait photography",
    "Wedding videography", "YouTube video editing", "TikTok content", "Reel editing",
    "Voiceover", "Voice acting", "Jingle creation", "Sound design",
  ],
  "Events": [
    "DJ", "MC / Host", "Event setup", "Event teardown", "Catering assist",
    "Decoration", "Balloon arrangements", "Floral arrangements", "Valet coordination",
    "Photo booth operation", "Event photography", "Event videography",
    "Live musician", "Singer", "Band", "Sound equipment setup", "Lighting setup",
    "AV technician", "Stage setup", "Wedding planning assist", "Party planning",
    "Birthday party host", "Kids entertainment", "Face painting",
    "Security / door person", "Bartending", "Cocktail mixing",
    "Tent & table setup", "Chair & table rental coordination",
  ],
  "Food & Cooking": [
    "Personal chef", "Meal prep (weekly)", "Meal prep (daily)", "Baking",
    "Cake decorating", "Cookie decorating", "Cooking lessons", "Baking lessons",
    "Catering (small events)", "Catering (large events)", "BBQ / Grill master",
    "Smoothie & juice prep", "Vegan / plant-based cooking", "Keto meal prep",
    "Cultural cuisine specialist", "Soul food", "Mexican cuisine", "Asian cuisine",
    "Italian cuisine", "Caribbean cuisine", "African cuisine", "Dessert making",
    "Chocolate making", "Candy making", "Food truck operation", "Food styling",
    "Recipe development", "Nutrition planning", "Dietary meal planning",
  ],
  "Technology & IT": [
    // Cloud & Infrastructure
    "AWS Cloud (EC2, S3, Lambda)", "Azure Cloud", "Google Cloud Platform",
    "Cloud architecture", "Cloud migration", "Serverless deployment",
    "Docker & containers", "Kubernetes", "CI/CD pipelines",
    // Networking
    "Network setup & configuration", "WiFi setup & optimization", "Router configuration",
    "Network security", "Firewall configuration", "VPN setup",
    "Cisco networking", "Network troubleshooting", "Cable management & wiring",
    "Ethernet installation", "Network monitoring", "CCNA skills",
    // Cybersecurity
    "Cybersecurity assessment", "Penetration testing", "Security auditing",
    "Malware removal", "Data recovery", "Encryption setup",
    "Security camera installation", "Access control systems",
    // Software Development
    "Web development (frontend)", "Web development (backend)", "Full-stack development",
    "Mobile app development", "React / Next.js", "Python development",
    "JavaScript / TypeScript", "Database management", "SQL / PostgreSQL",
    "API development", "WordPress development", "Shopify setup",
    "E-commerce setup", "Landing page development",
    // General IT
    "Computer repair", "Laptop repair", "PC building", "Hardware upgrade",
    "Smart home installation", "Smart home programming", "Home automation",
    "Printer setup", "Software installation", "Data backup",
    "Email setup", "Microsoft 365 setup", "Google Workspace setup",
    "Phone repair (screen)", "Phone repair (battery)", "Tablet repair",
    "TV setup & calibration", "Streaming device setup", "Gaming console repair",
    // Data & Analytics
    "Data analysis", "Excel / spreadsheet expert", "Data visualization",
    "Business intelligence", "SQL queries", "Python data scripts",
    "Web scraping", "Automation scripting",
    // AI & Emerging Tech
    "AI tool setup", "ChatGPT / AI integration", "Automation setup (Zapier, Make)",
    "Bot development", "3D printing setup",
  ],
  "Auto & Vehicle": [
    "Car detailing (interior)", "Car detailing (exterior)", "Full detail",
    "Oil change", "Tire change", "Tire rotation", "Battery replacement",
    "Battery jump start", "Brake pad replacement", "Brake inspection",
    "Basic diagnostics", "Check engine light diagnosis",
    "Air filter replacement", "Spark plug replacement", "Fluid top-off",
    "Headlight / taillight replacement", "Wiper blade replacement",
    "Car wash (hand)", "Ceramic coating", "Paint correction",
    "Window tinting", "Vinyl wrap", "Dent removal (paintless)",
    "Scratch removal", "Upholstery cleaning", "Leather conditioning",
    "Car audio installation", "Dashcam installation", "GPS tracker install",
    "Motorcycle maintenance", "Bicycle repair", "Bicycle tune-up",
    "Electric scooter repair", "Boat cleaning", "RV cleaning",
    "Trailer maintenance", "Pre-purchase inspection",
  ],
  "Hair & Beauty": [
    "Haircuts (men)", "Haircuts (women)", "Haircuts (kids)", "Fades & tapers",
    "Styling", "Blowouts", "Braiding", "Box braids", "Knotless braids",
    "Cornrows", "Locs (starting)", "Locs (maintenance)", "Locs (retwist)",
    "Silk press", "Natural hair care", "Color / highlights", "Balayage",
    "Weave install", "Wig install", "Wig customization", "Wig making",
    "Nails (manicure)", "Nails (pedicure)", "Acrylic nails", "Gel nails",
    "Nail art", "Press-on nails (custom)", "Lash extensions", "Lash lift",
    "Eyebrow threading", "Eyebrow shaping", "Waxing (face)", "Waxing (body)",
    "Makeup (everyday)", "Makeup (bridal)", "Makeup (special event)",
    "Henna / Mehndi", "Skincare consultation", "Facial treatments",
    "Teeth whitening", "Spray tan", "Body scrub",
    "Barber services (mobile)", "Hair consultation",
  ],
  "Fitness & Wellness": [
    "Personal training", "Group fitness training", "Yoga instruction",
    "Pilates instruction", "Dance lessons (hip hop)", "Dance lessons (salsa)",
    "Dance lessons (contemporary)", "Dance lessons (ballet)",
    "Martial arts instruction", "Boxing training", "Kickboxing",
    "Self-defense classes", "Swimming instruction", "Sports coaching (basketball)",
    "Sports coaching (football)", "Sports coaching (soccer)", "Sports coaching (baseball)",
    "Sports coaching (tennis)", "Golf instruction", "Running coach",
    "CrossFit training", "Strength training", "Weight loss coaching",
    "Nutrition coaching", "Meal plan creation", "Meditation instruction",
    "Breathwork", "Life coaching", "Wellness coaching",
    "Stretching & mobility", "Physical therapy exercises", "Senior fitness",
    "Prenatal fitness", "Postnatal fitness", "Kids fitness",
  ],
  "Transportation": [
    "Airport rides", "Airport pickup", "Carpooling", "Long distance driving",
    "Medical transport", "Designated driver", "Delivery driving",
    "Furniture delivery", "Appliance delivery", "Same-day delivery",
    "Package courier", "Food delivery (personal)", "Grocery delivery",
    "Moving truck driving", "Trailer towing", "Vehicle transport",
    "Motorcycle transport", "Ride to appointments", "School pickup / dropoff",
    "Event shuttle", "Wedding transportation", "Errand running (driving)",
  ],
  "Education & Tutoring": [
    // Academic
    "Math tutoring (elementary)", "Math tutoring (middle school)", "Math tutoring (high school)",
    "Algebra", "Geometry", "Calculus", "Statistics",
    "English / writing tutoring", "Reading tutoring", "Science tutoring",
    "Biology", "Chemistry", "Physics", "History / social studies",
    "SAT / ACT prep", "GED prep", "College application help", "Essay writing",
    // Technology
    "Computer basics", "Microsoft Office", "Google Suite",
    "Coding (Python)", "Coding (JavaScript)", "Coding (Java)", "Coding (C++)",
    "Web development tutoring", "App development tutoring",
    "AWS certification prep", "CompTIA A+ prep", "CompTIA Network+ prep",
    "CompTIA Security+ prep", "CCNA prep", "Cybersecurity fundamentals",
    "Data science basics", "Machine learning basics", "AI fundamentals",
    "Excel advanced", "SQL basics", "Linux basics",
    // Creative
    "Music lessons (piano)", "Music lessons (guitar)", "Music lessons (drums)",
    "Music lessons (bass)", "Music lessons (violin)", "Music lessons (voice / singing)",
    "Music theory", "Songwriting", "Beat making lessons",
    "Drawing lessons", "Painting lessons", "Digital art lessons",
    "Photography lessons", "Video editing lessons", "Graphic design lessons",
    // Languages
    "English (ESL)", "Spanish", "French", "German", "Mandarin",
    "Japanese", "Korean", "Arabic", "Portuguese", "Sign language (ASL)",
    // Business & Life
    "Financial literacy", "Budgeting basics", "Investment basics",
    "Business planning", "Entrepreneurship", "Marketing basics",
    "Public speaking", "Interview prep", "Resume building",
    "Study skills", "Time management", "Organization skills",
  ],
  "Trades & Skilled Labor": [
    "Electrical (licensed)", "Electrical (basic / unlicensed)",
    "Plumbing (licensed)", "Plumbing (basic / unlicensed)",
    "HVAC (licensed)", "HVAC (basic)", "General contracting",
    "Carpentry", "Woodworking", "Cabinet making", "Framing",
    "Roofing", "Siding", "Masonry", "Concrete work",
    "Welding", "Metal fabrication", "Blacksmithing",
    "Drywall installation", "Drywall finishing", "Mudding & taping",
    "Tiling (floor)", "Tiling (wall)", "Tiling (shower)",
    "Flooring installation (hardwood)", "Flooring installation (vinyl)",
    "Flooring installation (carpet)", "Painting (professional)",
    "Wallpaper installation", "Crown molding", "Trim work",
    "Window installation", "Door installation", "Garage door repair",
    "Appliance installation", "Appliance repair",
    "Locksmith services", "Glass repair / replacement",
    "Solar panel installation", "EV charger installation",
    "Home inspection", "Mold inspection", "Mold remediation",
    "Insulation installation", "Gutter installation",
  ],
  "Business & Professional": [
    "Bookkeeping", "Tax preparation", "QuickBooks setup", "Accounting (basic)",
    "Business consulting", "Business plan writing", "Grant writing",
    "Legal document preparation", "Notary services", "Contract review",
    "Real estate assistance", "Property management help",
    "Virtual assistant", "Administrative support", "Data entry",
    "Customer service", "Phone answering", "Email management",
    "Calendar management", "Travel planning", "Meeting coordination",
    "Transcription", "Translation services", "Proofreading",
    "Project management", "Event coordination",
    "Marketing consulting", "SEO consulting", "Social media strategy",
    "Google Ads management", "Facebook Ads management", "TikTok marketing",
    "Email marketing", "Newsletter creation", "CRM setup",
    "Salesforce administration", "HubSpot setup",
    "Inventory management", "Supply chain assistance",
    "HR assistance", "Recruiting help", "Background check processing",
  ],
  "Health & Caregiving": [
    "Elderly companion care", "Senior home care", "Alzheimer's care companion",
    "Post-surgery care assistance", "Disability assistance",
    "Medication reminders", "Light housekeeping (elderly)",
    "Meal preparation (elderly)", "Transportation to appointments",
    "Hospice companion", "Respite care",
    "Newborn care", "Postpartum doula", "Night nurse (newborn)",
    "Special needs care", "Autism companion",
    "Physical therapy assistant", "Occupational therapy exercises",
    "First aid certified", "CPR certified",
    "Mental health companion", "Sobriety companion",
    "Errand running (health related)", "Medical equipment setup",
  ],
  "Arts & Entertainment": [
    "Live music performance", "Singer for events", "Rapper / MC",
    "Band for hire", "Acoustic guitar performance", "Piano performance",
    "Jazz ensemble", "Karaoke host", "Open mic host",
    "Stand-up comedy", "Improv comedy", "Magic show",
    "Clown / kids entertainer", "Balloon twisting", "Puppet show",
    "Storytelling", "Poetry reading", "Spoken word",
    "Art installation", "Sculpture", "Pottery",
    "Calligraphy", "Hand lettering", "Custom signs",
    "Mural painting", "Graffiti art (legal)", "Street art",
    "Custom portrait painting", "Caricature drawing",
    "Costume making", "Cosplay creation", "Props making",
    "Film production assist", "Extra / background actor",
    "Modeling (product)", "Modeling (fashion)", "Brand ambassador",
  ],
  "Outdoor & Sports": [
    "Lawn games setup", "Sports field setup", "Sports equipment assembly",
    "Basketball coaching (private)", "Football coaching (private)",
    "Soccer coaching (private)", "Baseball / softball coaching",
    "Tennis coaching", "Golf lessons", "Swimming lessons",
    "Skateboarding lessons", "Surfing lessons", "Kayak guide",
    "Fishing guide", "Hunting guide", "Hiking guide",
    "Camping setup help", "Outdoor event setup",
    "Boat cleaning", "Boat maintenance (basic)",
    "Horse care / grooming", "Horse riding lessons",
    "Dog training", "Puppy training", "Obedience training",
    "Archery instruction", "Rock climbing instruction",
    "Ski / snowboard instruction", "Ice skating instruction",
  ],
};
